# docker-compose.yml

services:
  back-end:
    build:
      context: ./back-end/back-end
    ports:
      - "9090:9090"

  front-end:
    build:
      context: ./front-end
    ports:
      - "8080:80"
    depends_on:
      - back-end